#!/usr/bin/env bash
# with-tmux-audit.sh — the ONLY approved way to intercept `tmux` calls.
#
# Replaces the hand-rolled PATH shim that caused the 2026-07-18 runaway
# (~12 GB calls.log from a recursive bare-`exec tmux` + unbounded append).
# This wrapper is correct by construction:
#
#   1. REAL tmux is resolved to an ABSOLUTE path before PATH is touched.
#   2. A recursion guard (T2H_AUDIT_ACTIVE) prevents re-logging nested calls.
#   3. calls.log is BYTE-CAPPED (default 10 MiB; never unbounded).
#   4. Every call is forced onto an ISOLATED -L socket — the user's live tmux
#      ($TMUX / default socket) is never connected to for anything but
#      read-only capture (PRD §0).
#   5. Teardown kills sessions on OUR socket by name only, via trap. NEVER
#      kill-server.
#
# Usage:
#   scripts/with-tmux-audit.sh [--socket NAME] [--logcap BYTES] [--] <cmd...>
# Example:
#   scripts/safe-run.sh -- scripts/with-tmux-audit.sh -- \
#       ./zig-out/bin/tmux-2html pane --visible --output /tmp/out.html
set -uo pipefail

# 1. Resolve REAL tmux to an absolute path BEFORE any PATH manipulation.
REAL_TMUX="$(command -v tmux || true)"
[ -n "$REAL_TMUX" ] || { echo "with-tmux-audit: tmux not found on PATH" >&2; exit 2; }
case "$REAL_TMUX" in /*) :;; *) REAL_TMUX="$PWD/$REAL_TMUX";; esac
[ -x "$REAL_TMUX" ] || { echo "with-tmux-audit: resolved tmux not executable: $REAL_TMUX" >&2; exit 2; }

SOCK="t2h-audit-$$"
LOGCAP=$((10 * 1024 * 1024))   # 10 MiB hard cap on calls.log
while [ $# -gt 0 ]; do
  case "$1" in
    --socket) SOCK="$2";  shift 2;;
    --logcap) LOGCAP="$2"; shift 2;;
    --) shift; break;;
    -h|--help) sed -n '2,26p' "$0"; exit 0;;
    *) echo "with-tmux-audit: unknown arg: $1 (see --help)" >&2; exit 2;;
  esac
done
[ $# -gt 0 ] || { echo "with-tmux-audit: no command given (-- <cmd>)" >&2; exit 2; }

# Scratch on real disk (XDG cache / HOME, not /tmp tmpfs). Bounded by LOGCAP.
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"
SCRATCH="${T2H_SCRATCH:-$CACHE/t2h-audit}/$$"
mkdir -p "$SCRATCH" || { echo "with-tmux-audit: cannot create $SCRATCH" >&2; exit 2; }
SHIM="$SCRATCH/tmux"
CALLS="$SCRATCH/calls.log"
: > "$CALLS"

# 2–4. Generate the approved shim. Quoted heredoc => fully literal; the four
# config values are passed in via env, so there is no escaping to get wrong and
# no bare `tmux` for a future grep-based audit to flag.
export T2H_AUDIT_REAL_TMUX="$REAL_TMUX"
export T2H_AUDIT_SOCK="$SOCK"
export T2H_AUDIT_CALLS="$CALLS"
export T2H_AUDIT_LOGCAP="$LOGCAP"
cat > "$SHIM" <<'SHIM_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/with-tmux-audit.sh — DO NOT EDIT.
# Recursion-guarded + log-capped; execs the REAL tmux (absolute path) on an
# isolated -L socket so the user's live tmux is never touched (PRD §0).
if [ -z "${T2H_AUDIT_ACTIVE:-}" ]; then
  export T2H_AUDIT_ACTIVE=1
  __calls="${T2H_AUDIT_CALLS:?unset}"
  __cap="${T2H_AUDIT_LOGCAP:?unset}"
  __sz=$(stat -c %s "$__calls" 2>/dev/null || echo 0)
  if [ "$__sz" -lt "$__cap" ]; then
    printf 'tmux-call: %s\n' "$*" >> "$__calls"
  elif [ "$__sz" -lt $(( __cap + 256 )) ]; then
    printf '[audit] calls.log cap (%s bytes) reached; logging stopped\n' "$__cap" >> "$__calls"
  fi
fi
exec "${T2H_AUDIT_REAL_TMUX:?unset}" -L "${T2H_AUDIT_SOCK:?unset}" "$@"
SHIM_EOF
chmod +x "$SHIM"

# 5. Scoped teardown: kill sessions on OUR socket by name only. Never kill-server.
cleanup() {
  if [ -x "$REAL_TMUX" ]; then
    local sessions
    sessions="$("$REAL_TMUX" -L "$SOCK" list-sessions -F '#{session_name}' 2>/dev/null || true)"
    if [ -n "$sessions" ]; then
      while IFS= read -r s; do
        [ -n "$s" ] && "$REAL_TMUX" -L "$SOCK" kill-session -t "$s" 2>/dev/null || true
      done <<< "$sessions"
    fi
  fi
  rm -rf "$SCRATCH" 2>/dev/null || true
}
trap cleanup EXIT

echo "with-tmux-audit: socket=-L $SOCK  log=$CALLS (cap ${LOGCAP}B)  real=$REAL_TMUX" >&2

# Run the audited command with the shim's DIRECTORY first on PATH (PATH entries
# are directories; $SHIM is the file). T2H_AUDIT_ACTIVE is NOT set here, so the
# command's own tmux calls get logged exactly once.
rc=0
PATH="$SCRATCH:$PATH" "$@" || rc=$?

# Show the (bounded) call log, then trap EXIT cleans up. NOTE: redirect order
# matters — `>&2 2>/dev/null` (stdout->stderr, then hush head's own stderr);
# the reverse sends BOTH to /dev/null and the dump looks empty.
echo "---- calls.log ----" >&2
head -c "$LOGCAP" "$CALLS" >&2 2>/dev/null || true
echo "-------------------" >&2
exit "$rc"